language: python

env:
  - ENV=testing

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database stackoverflow;' -U postgres
  - psql -c 'create database stackoverflow_tests;' -U postgres

script:
  - python3 -m pytest --cov=app

after_success: coveralls
